[world]
name = "Grim Block"
seed = "grimblock-v0.0.0"
description = "Grim Block"
website = "https://grimblock.gg"

[namespace]
default = "GRIMBLOCK"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x07b5bf434c7fa4a32849b6f38edcfa89619b2b9d2645b32653822c21b20119ce"
account_address = "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753"
keystore_path = "./keystore_sepolia.json"

[migration]
order_inits = ["GRIMBLOCK-Play"]
disable_multicall = true

[writers]
"GRIMBLOCK" = ["GRIMBLOCK-Play"]

[init_call_args]
"GRIMBLOCK-Play" = []
