[world]
name = "Grim Block"
seed = "grimblock-v0.0.1"
description = "Grim Block"
website = "https://grimblock.gg"

[namespace]
default = "GRIMBLOCK"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x00d62ce2486c4ba0caaa0f63013044b16a70eb269cf76c832893b1df6e3f23f0"
account_address = "0x041aad5a7493b75f240f418cb5f052d1a68981af21e813ed0a35e96d3e83123b"
keystore_path = "./keystore.json"

[migration]
order_inits = ["GRIMBLOCK-Play"]
disable_multicall = true

[writers]
"GRIMBLOCK" = ["GRIMBLOCK-Play"]

[init_call_args]
"GRIMBLOCK-Play" = []
